version: '3.8'

services:
  mongodb:
    image: mongo:6
    container_name: volt-mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USER:-admin}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD:-changeme}
    volumes:
      - mongodb_data:/data/db
    networks:
      - volt-network
    # Port removed - MongoDB only accessible within Docker network for security

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: volt-backend
    restart: unless-stopped
    environment:
      NODE_ENV: production
      PORT: 5000
      MONGODB_URI: mongodb://${MONGO_ROOT_USER:-admin}:${MONGO_ROOT_PASSWORD:-changeme}@mongodb:27017/volt?authSource=admin
      JWT_SECRET: ${JWT_SECRET:-your-secret-key-change-this}
      SOLANA_RPC: ${SOLANA_RPC:-https://api.mainnet-beta.solana.com}
      EMAIL_USER: ${EMAIL_USER}
      EMAIL_PASS: ${EMAIL_PASS}
      FRONTEND_URL: ${FRONTEND_URL:-http://localhost:3000}
    depends_on:
      - mongodb
    networks:
      - volt-network
    ports:
      - "5000:5000"

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: volt-frontend
    restart: unless-stopped
    depends_on:
      - backend
    networks:
      - volt-network
    ports:
      - "80:80"

networks:
  volt-network:
    driver: bridge

volumes:
  mongodb_data:
    driver: local
